cmake_minimum_required(VERSION 3.23)
project(hello_audio CXX)

find_package(fmt REQUIRED)

add_executable(hello_audio src/main.cpp)
target_compile_features(hello_audio PRIVATE cxx_std_17)
target_link_libraries(hello_audio PRIVATE fmt::fmt)

if(WIN32)
    find_package(portaudio REQUIRED)
    target_sources(hello_audio PRIVATE src/audio_windows.cpp)
    target_link_libraries(hello_audio PRIVATE portaudio_static)
elseif(APPLE)
    target_sources(hello_audio PRIVATE src/audio_macos.cpp)
    target_link_libraries(hello_audio PRIVATE "-framework CoreAudio")
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    find_package(ALSA REQUIRED)
    target_sources(hello_audio PRIVATE src/audio_linux.cpp)
    target_link_libraries(hello_audio PRIVATE ALSA::ALSA)
endif()
